version: '3.6'

services:
  orchestrator:
    build: ./orchestrator
    ports:
      - '80:4000'
    environment:
      - 'APP_URL=http://app-service:4002'
      - 'USER_URL=http://user-service:4001'
  user-service:
    build: ./service/users
    ports:
      - '4001:4001'

  app-service:
    build: ./service/app
    ports:
      - '4002:4002'
